[package]
name = "webfinger"
version = "0.1.0"
authors = ["Stuart Reilly <stu@reilly-family.co.uk>"]

[dependencies]
hyper = "*"
hyper-native-tls = "*"
error-chain = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
chrono = { version = "*", features = ["serde"]}