[package]
name = "webfinger"
version = "0.1.0"
authors = ["Stuart Reilly <stu@reilly-family.co.uk>"]

[dependencies]
hyper = "0.10"
hyper-native-tls = "0.2"
error-chain = "0.10"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"]}